# Generated by Django 3.0.6 on 2020-05-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('category', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='menupics')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='collections')),
                ('menu', models.ManyToManyField(to='main_app.Menu')),
            ],
        ),
    ]
