# Generated by Django 3.0.6 on 2020-05-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('img', models.ImageField(upload_to='clientpics')),
                ('location', models.CharField(blank=True, max_length=25)),
                ('contact', models.IntegerField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('menu', models.ManyToManyField(to='main_app.Menu')),
            ],
        ),
    ]
