# Generated by Django 3.0.6 on 2020-05-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.IntegerField(blank=True),
        ),
    ]
