# Generated by Django 3.0.6 on 2020-05-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200523_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
